I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 172, in script
    show jonathan normal:
Exception: Image 'jonathan' does not accept attributes 'normal'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 172, in script
    show jonathan normal:
  File "C:\Users\Janet\Desktop\renpy-8.2.1-sdk\renpy\ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Janet\Desktop\renpy-8.2.1-sdk\renpy\ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "C:\Users\Janet\Desktop\renpy-8.2.1-sdk\renpy\exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\Janet\Desktop\renpy-8.2.1-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\Janet\Desktop\renpy-8.2.1-sdk\renpy\display\displayable.py", line 246, in _duplicate
    args.extraneous()
  File "C:\Users\Janet\Desktop\renpy-8.2.1-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'jonathan' does not accept attributes 'normal'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
The Mystery of the Missing Files 1.0
Thu Mar 21 02:03:14 2024
